name: CI

on:
  push:
    branches:
      - '*'
      - '**/*'

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          yarn install

      - name: Lint
        run: |
          yarn run lint
          yarn run lint:css

      - name: Format
        run: |
          yarn run format

      - name: Typecheck
        run: |
          yarn run typecheck

      - name: Test
        run: |
          yarn run test
